name: Cocoapods Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v2

      - name: Publish to CocoaPod
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          ./scripts/release_pods.sh
